### PR TITLE
Login UI Update

### PR DESCRIPTION
**Pull request by MonsieurMantis**
I fixed the UI. No merge conflicts please.

### CODE REVIEW

**Comment by MonsieurMantis** [comment]
Linter Passed 😎

**Review by kthchew — APPROVED** [review]
lgtm but conflict needs fixing

**Review by kthchew — CHANGES_REQUESTED** [review]
There is not only a conflict, but merging with main will also break the layout even after resolving it

https://catcorp-frontend-ochg2azej-kenneths-projects-5159d859.vercel.app/

**Review by kthchew — APPROVED** [review]
Nevermind, was able to fix, merging

**Pull request merged**
